[build]
target = "aarch64-unknown-linux-gnu"

[target.aarch64-unknown-linux-gnu]
linker = "/bin/aarch64-linux-gnu-gcc"
runner = "./target-runner.sh"
rustflags = [
    "-C", "link-arg=-B/usr/local/bin/mold"
]
strip = { path = "/bin/aarch64-linux-gnu-strip" }

[env]
CROSS_COMPILE = "/bin/aarch64-linux-gnu-"
#PKG_CONFIG_PATH = "/usr/lib/pkgconfig"
PKG_CONFIG_PATH = "/usr/include"
PKG_CONFIG_SYSROOT_DIR = "/usr/local/lib/pkgconfig"

RKAIQ_INCLUDE_DIR = "/usr/include/rkaiq"
TARGET_SYSROOT_DIR = "/usr/local/lib/pkgconfig"

TARGET_SSH_HOST = "192.168.18.76"
TARGET_SSH_PSWD = ""

[http]
# proxy = "http://192.168.2.11:8080"

[net]
git-fetch-with-cli = true
# offline = true
